[build]
  publish = "build" # Use "dist" if you're using Vue or another framework
  command = "npm run build" # Replace with your build command

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
